### ISSUE TITLE
ERR_PACKAGE_PATH_NOT_EXPORTED on fastify-openapi-glue

### ISSUE THREAD

**Issue by yukha-dw** [digital-loukoum/tsc-esm#10]
First of all, i'm sorry if this might be an external issue, but everything is working fine on tsc.

Does anyone has ever stumble to this issue?
```
[tsc-esm] Could not build: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in node_modules\fastify-openapi-glue\package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:645:7)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at resolve (file:///C:/repo/github/place-server/node_modules/@digitak/grubber/utilities/patchJsImports.js:8:6)
    at file:///C:/repo/github/place-server/node_modules/@digitak/grubber/utilities/patchJsImports.js:38:32
    at addJsExtensions (file:///node_modules/@digitak/grubber/utilities/addJsExtensions.js:12:31) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

I've added "type": "module" in package.json and updated my tsconfig.json to ES Module.
If I use tsc, it builds successfully, but not on tsc-esm.
Thanks

**Comment by Gin-Quin** [comment]
It seems likely to be an external issue.

Try the different fixes proposed in [this thread](https://stackoverflow.com/questions/62246824/error-err-package-path-not-exported-no-exports-main-resolved-in-app-node-m).

**Comment by Gin-Quin** [comment]
I'm closing this, you can reopen it if necessary.
